# Generated by Django 4.2.7 on 2025-04-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mouse_movements', models.JSONField(default=list)),
                ('scroll_events', models.JSONField(default=list)),
                ('typing_patterns', models.JSONField(default=list)),
                ('click_patterns', models.JSONField(default=list)),
                ('touch_interactions', models.JSONField(default=list)),
                ('user_agent', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_id', models.CharField(max_length=255)),
                ('response_time', models.IntegerField(help_text='Response time in milliseconds')),
                ('navigation_start', models.BigIntegerField(help_text='Timestamp of navigation start (ms since epoch)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
