# Generated by Django 4.2.7 on 2025-06-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_useractivity_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='mode',
            field=models.PositiveIntegerField(choices=[(0, 'BOT'), (1, 'USER'), (2, 'NOT_LABELED')], default=2),
        ),
    ]
