# Generated by Django 4.2.7 on 2025-06-14 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_pipmsg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pipmsg',
            old_name='user_agent',
            new_name='message',
        ),
    ]
