version: '3.8'
services:
  captchaapi:
    container_name: 'captchaapi'
    image: '${API_IMAGE}'
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/captchaapi/staticfiles/
      - media_volume:/captchaapi/mediafiles/
      - /var/certbot/conf:/etc/letsencrypt/
      - /var/certbot/www/:/var/www/certbot/
    expose:
      - 8000

  nginx:
    container_name: 'nginx'
    image: '${NGINX_IMAGE}'
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_volume:/captchaapi/staticfiles/
      - media_volume:/captchaapi/mediafiles/
      - /var/certbot/conf:/etc/letsencrypt/
      - /var/certbot/www/:/var/www/certbot/
      - ./nginx.conf:/nginx/nginx.conf:ro


  certbot:
    image: certbot/certbot:latest
    volumes:
      - /var/certbot/conf:/etc/letsencrypt/
      - /var/certbot/www/:/var/www/certbot/
#    entrypoint: /bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot --quiet; sleep 12h & wait $${!}; done;'
#    command: certonly --webroot -w /var/www/certbot/ -d backend.btechtutor.com --email huesolution7@gmail.com --agree-tos
    depends_on:
      - nginx

volumes:
  static_volume:
  media_volume:


