# Generated by Django 4.2.7 on 2025-04-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='mode',
            field=models.PositiveIntegerField(choices=[(0, 'BOT'), (1, 'USER'), (3, 'NOT_LABELED')], default=3),
        ),
    ]
