# nginx.conf
upstream api_upstream {
    server captchaapi:8000;
}

# server {
#    listen 443 ssl;
#    server_name cbe.jhub.in;
#     ssl_certificate /etc/letsencrypt/live/cbe.jhub.in/fullchain.pem;
#     ssl_certificate_key /etc/letsencrypt/live/cbe.jhub.in/privkey.pem;
#     access_log /var/log/nginx/access.log;
#     error_log /var/log/nginx/error.log;
#    client_max_body_size 200M;
#    location / {
#       proxy_set_header X-Url-Scheme $scheme;
#       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#       proxy_set_header Host $http_host;
#       proxy_set_header X-Forwarded-Proto $scheme;
#       proxy_redirect off;
#       proxy_pass http://captchaapi:8000/;
#      }
#     location /static/ {
#         alias /captchaapi/staticfiles/;
#     }
#
#     location /media/ {
#         alias /captchaapi/mediafiles/;
#     }
#  }

# server {
#     listen 80;
#     server_name cbe.jhub.in;
#
#     location /.well-known/acme-challenge/ {
#         root /var/www/certbot/;
#         allow all;
#     }
#     location / {
#         return 301 https://$host$request_uri;
#     }
# }
server {
    listen 80;
    server_name cbe.jhub.in;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
        try_files $uri =404;
    }

    location / {
        proxy_pass http://api_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

